# -*- coding: utf-8 -*-
"""Fibonacci Series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZUWfifAowTj1xdBrJqWv8khsn6XDht0
"""

import time
gr=1.61803398874989484820
term1=1
while(1):
  term2=round(term1*gr)
  term1=term2
  print(term1)
  time.sleep(1)